---
extends: "default"

rules:
  braces:
    max-spaces-inside: 1
    level: "error"
  brackets:
    max-spaces-inside: 1
    level: "error"
  colons:
    max-spaces-after: 1
    level: "error"
  commas:
    max-spaces-after: 1
    level: "error"
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
    level: "error"
  comments-indentation: false
  empty-lines:
    max: 3
    level: "error"
  hyphens:
    max-spaces-after: 1
    level: "error"
  indentation:
    spaces: "consistent"
    indent-sequences: true
    level: "error"
  line-length: "disable"
  new-line-at-end-of-file: "enable"
  new-lines:
    type: "unix"
    level: "error"
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  quoted-strings:
    quote-type: "double"
    level: "error"
  trailing-spaces: "enable"
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
    level: "error"
