---
-
  name: "service | Manage the sshd service"
  become: true
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: "{{ sshd_service_state }}"
    enabled: "{{ sshd_service_enabled }}"
